# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/${SECRET_DB_SCHEMA_NAME}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&sessionVariables=sql_mode=''
    username: ${SECRET_DB_USER}
    password: ${SECRET_DB_PASS}
    initialization-mode: always

  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: TESTTEST
  expiration: 86400000