# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/pcatteldb?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&sessionVariables=sql_mode=''
    username: pcattel
    password: 0HI42K74
    platform: local
    initialization-mode: always

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000
