# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:
  datasource:
    url: jdbc:mysql://proxysql.master.meliseginf.com:6612/${SECRET_DB_SCHEMA_NAME}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8&sessionVariables=sql_mode=''
    username: ${SECRET_DB_USER}
    password: ${SECRET_DB_PASS}

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000